# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3993d21909e7813299cdb9a38ca29003b6da4ebe5ca09ceb46a5fc073cb810a1b471fc910552ba78bd85f3cfe070d7298e8e72a39a73faf68d2a6b4299987fc

test:
  secret_key_base: ef4991c255d8c4283c39a192caf4d0bd6ea4f3cd2db718919f89309d23b521f3348b9aac67c3cb230d2051bc7ded3ddea649f3cbd1346ea6a03fea8e8c04cd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
